name: spacextracker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  flutter_native_splash: ^1.1.5+1
  flutter_staggered_animations: ^1.0.0
  provider: ^5.0.0
  intl: ^0.17.0
  transparent_image: ^2.0.0
  youtube_player_iframe: ^2.0.0
  flutter_inappwebview: ^5.3.2
  flutter_snake_navigationbar: ^0.5.0
  flutter_countdown_timer: ^4.0.2
  delayed_display: ^2.0.0
  video_player: ^2.1.1
  sizer: ^2.0.13
  device_preview: ^0.7.1
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#201F48"
  image: assets/images/RocketIcon.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
